export { default as Nav} from './nav/nav'
// export { default as Faq} from './faq'
export { default as CaringCup} from './caringcup/caringCup'
export { default as Hero} from './hero/hero'
export { default as ShopAndSwirl} from './shopandswirl/shopAndSwirl'
// export { default as Reviews} from './reviews'
export { default as OurStory} from './ourstory/ourStory'
export { default as Footer} from './footer/footer'
